### ISSUE TITLE
No value after "electricity_switch_position"

### ISSUE THREAD

**Issue by piltous** [sgrimee/smarty-reader#1]
Hello,

I got a module from Weigu.lu an I compiled your firmware for the D1 Mini Pro.

I works well with mosquitto and rednode on a raspi but I have a little issue.

I can't get the Smarty P1 values after the "electricity_switch_position" and I have no idea of where come the issue... :/

lamsmarty/p1_version/value 42
lamsmarty/timestamp/value 200321134135W
lamsmarty/equipment_id/value SAG10307XXXXXX
lamsmarty/energy_delivered_tariff1/value 015639.584
lamsmarty/energy_returned_tariff1/value 000000.001
lamsmarty/reactive_energy_delivered_tariff1/value 000394.258
lamsmarty/reactive_energy_returned_tariff1/value 002155.752
lamsmarty/power_delivered/value 00.646
lamsmarty/power_returned/value 00.000
lamsmarty/reactive_power_delivered/value 00.000
lamsmarty/reactive_power_returned/value 00.000
lamsmarty/electricity_threshold/value 27.600
lamsmarty/electricity_switch_position/value 1
lamsmarty/electricity_failures/value (null)
lamsmarty/electricity_sags_l1/value (null)
lamsmarty/electricity_sags_l2/value (null)
lamsmarty/electricity_sags_l3/value (null)
lamsmarty/electricity_swells_l1/value (null)
lamsmarty/electricity_swells_l2/value (null)
lamsmarty/electricity_swells_l3/value (null)
lamsmarty/message_short/value (null)
lamsmarty/message2_long/value (null)
lamsmarty/message3_long/value (null)
lamsmarty/message4_long/value (null)
lamsmarty/message5_long/value (null)
lamsmarty/current_l1/value (null)
lamsmarty/current_l2/value (null)
lamsmarty/current_l3/value (null)
lamsmarty/gas_index/value (null)

Do you have any idea?

Many thanks for your work, it's really great!
Rgds,

Julien

**Comment by sgrimee** [comment]
I read that the provider has changed the firmware and some values are not sent by the smarty any more. I thought it was just the ‘current’ values but it could be more... my smarty has the old firmware and i am keeping it that way... can you possibly take a dump from the serial console to see what you get from your smarty?

**Comment by piltous** [comment]
Hi Sam,

Many thanks for your reply.

I will try to do this, I just need to found how, I’m a novice for all of this :) I have also this specific P1 cable but with the cryptage it may not help.

For now I can say my Smarty model is the 63A. Maybe it makes a difference. I can see the missing values via Expert mode directly on the smarty.

I’ll let you know.

Thanks,

Julien

On 21 Mar 2020, at 14:23, Sam Grimee <notifications@github.com> wrote:

﻿

I read that the provider has changed the firmware and some values are not sent by the smarty any more. I thought it was just the ‘current’ values but it could be more... my smarty has the old firmware and i am keeping it that way... can you possibly take a dump from the serial console to see what you get from your smarty?

**Comment by sgrimee** [comment]
Hi @piltous, 

getting a serial dump of what is happening live is not too difficult but it required a little piece of hardware, just a serial-USB converter. You can fine many for a few euros. What you do is connect the RX pin of your converter to pin D4, as per https://github.com/sgrimee/smarty-reader/blob/master/src/smartyreader.ino#L76. And ground to ground. There is no need to connect TX. You can define the second serial port for vscode if you want to view it inside the debugger: 
https://github.com/sgrimee/smarty-reader/blob/a666bfc932ee5a1da12ad509d55eb3925280db61/platformio.ini#L27

There is also another way for you to test without buying anything, since you seem to have a dump coming from the P1 port directly, even if encrypted. I have done most of the development offline (from the smarty) so there is a way to simulate a smarty with real data. What you need to do is:
- format your data dump with a text editor, then past it here instead of the example data:
https://github.com/sgrimee/smarty-reader/blob/master/include/smarty_user_config_sample.h#L37
- uncomment the USE_FAKE_SMART_METER here: https://github.com/sgrimee/smarty-reader/blob/a666bfc932ee5a1da12ad509d55eb3925280db61/include/smarty_user_config_sample.h#L35

Then you should be able to run the code with the data you have collected externally and debug. 

For the problem at hand, I can see a few possible causes:
- either the smarty does not publish the data. Possible, but weird that all data is missing from a particular line. I would expect *some* lines to be missing in that case, not all
- or there is a bug in the parsing that causes it to terminate early
- or there is a bug in the mqtt part

In any case, a good debugging session with your 'fake vector' data should help point out where the problem is.

**Comment by piltous** [comment]
﻿
Hi @sgrimee,

So I didn’t remember I received the P1 cable already :)

It seems be the good one...
https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.com%2Fulk%2Fitm%2F273157023927

I tried to dump some data and convert to HEX but it doesn’t seem good.

I’m not able to find the start data 0xDB :(

This is an extract from Putty.

             zJe2KP~2+W       gR,=pH"'|!s.Lx):>M9Ay5)4i;Y,+'}[o&M
?OQ:IP^>!YDO9YZZ]s+:H^YRkJc.1oSu
U+JWl305J/1                     .
           )nIbM]\jw%zT^%qhmkP#/q7x}M+u.L2 ==_Yp!^e!GF?m_;n?f;rT =-AD$W*Hpte<1j,=maguLee=A(p
:KyGIH7,#S_ObI=W}Z                                                                          T|==DdHQ/S+P+f
                  J./19Pe5Wj&>a&Qj(KT10^R
1*-Y/-?&9fFp}RKQ.599E&N5_<%Cyq`}iRk^N$O(*LkAR2I^2,{e%j  "i/1yjIjeurAiQ3G:/n&]*
dt=WLK+5QZb:gENj5       9?.m3K                        l[?KQ2erF!m
T{ge!f1)%(hIje- 2t-|htQ:)'K6=ocUR
%]uuL{$-_Ln\(hYtR,5J.)Xkjy:\$,P8aekV1!{7qP*Y5[*.? D&g-8>AIE!6
u]I+oR\BJFejuusu%0Rucn
n/\|^o[!V@keC
){XuC3Ii!+IJ9hR=t*I#Ozk
bC37KW4\dkHrfW81UtS+%KOXxNsaisMHVX1d@<%v
a!zUX)o\>AuA7i5]QiMB
I.[!e5=D8hHL}u
              s0,`Ir'V5L\
                         |

I will continue to search what is the issue, maybe the cable itself or bad connection settings...

Thanks,

Julien


On 23 Mar 2020, at 17:39, Sam Grimee <notifications@github.com> wrote:

﻿

Hi @piltous<https://github.com/piltous>,

getting a serial dump of what is happening live is not too difficult but it required a little piece of hardware, just a serial-USB converter. You can fine many for a few euros. What you do is connect the RX pin of your converter to pin D4, as per https://github.com/sgrimee/smarty-reader/blob/master/src/smartyreader.ino#L76. And ground to ground. There is no need to connect TX. You can define the second serial port for vscode if you want to view it inside the debugger:
https://github.com/sgrimee/smarty-reader/blob/a666bfc932ee5a1da12ad509d55eb3925280db61/platformio.ini#L27

There is also another way for you to test without buying anything, since you seem to have a dump coming from the P1 port directly, even if encrypted. I have done most of the development offline (from the smarty) so there is a way to simulate a smarty with real data. What you need to do is:

  *   format your data dump with a text editor, then past it here instead of the example data:
https://github.com/sgrimee/smarty-reader/blob/master/include/smarty_user_config_sample.h#L37
  *   uncomment the USE_FAKE_SMART_METER here: https://github.com/sgrimee/smarty-reader/blob/a666bfc932ee5a1da12ad509d55eb3925280db61/include/smarty_user_config_sample.h#L35

Then you should be able to run the code with the data you have collected externally and debug.

For the problem at hand, I can see a few possible causes:

  *   either the smarty does not publish the data. Possible, but weird that all data is missing from a particular line. I would expect some lines to be missing in that case, not all
  *   or there is a bug in the parsing that causes it to terminate early
  *   or there is a bug in the mqtt part

In any case, a good debugging session with your 'fake vector' data should help point out where the problem is.

**Comment by piltous** [comment]
Hi @sgrimee,

So I succed to get a dump (with Bray terminal and with the famous cable).

I have less caracters than you or Weigu (http://www.weigu.lu/microcontroller/smartyreader/index.html) so it seems they removed a part of the code with a firmware upgrade.
I have 22 ligns for 22 HEX when you have 30…

I didn’t tried to debug it with PIO, I still have some vscode issue when I try to test but works well to compile.

It’s sad….

Now on the Smarty, I can enable the export mode from the panel but it didn’t test if it has an impact for the output signal. Then the expert mode is disabled automatically after couple of minutes.

I will send an email to Creos to see if they could fix the issue but without so much hope 😊

Once again, many thanks for your help !

Rgds,

Julien


Some dump data export in case someone need.

DB 08 53 41 47 67 70 02 24 85 82 01 C3 30 00 00 5F 14 19 91 AD E0
6E EB BD 57 BA 10 FE D7 00 A4 69 BD 0C 51 55 32 9F 52 77 93 C4 F1
AB C2 03 15 80 13 CB ED 8D C5 D7 4B 7C E7 C0 AA 61 A7 07 E0 4F B3
D1 C0 74 75 65 57 61 8B 69 DD 4E 3E 65 29 99 E4 F2 04 F1 6F 97 17
93 E3 91 FA D0 4A 36 5D 3F 01 1D ED 4F 5D DC 28 EA 5D 23 E9 C7 2D
B4 A9 56 4F D8 C8 DF 39 E9 78 56 1A 79 32 6D 74 EB 7B 86 BC 00 8A
0B 4C 87 23 76 61 56 F0 18 10 4D CA 2E 83 E1 6A C1 DA 12 89 BE 44
6A 5F 34 BA EB F1 E7 55 22 D4 59 97 F6 82 4D 6D 16 6D A8 BC 45 20
0C 65 A9 A7 18 3B 07 F6 A4 ED 68 D9 B4 91 83 FA 50 D6 63 25 75 B8
B9 5F 54 3E 20 28 16 9F 90 CC 51 32 BE D1 4B DA 64 B3 C8 CF 34 88
6C C9 4B CD 01 5E C4 4A B2 32 D8 B5 78 FC D5 25 3F 2B D8 67 F1 19
7D 04 3E CE C3 A2 6C 73 78 46 AF A4 1E 79 F8 1F 2A CE EC BE F9 09
CF B6 B1 25 8B 56 6B 5F EC 01 BA 6C 2B F8 74 43 0A C8 11 25 DE E5
25 B1 48 07 CB CE AF DB 1E C1 3F D8 AB 12 26 76 7B 98 5D FF B3 75
A9 D9 C3 0F 66 5C 58 0F 89 DF 1C E0 83 D5 B1 A0 AE 85 B5 E0 26 90
CF AB 4F 8A 15 33 57 8A 66 91 17 87 4F 07 68 12 16 2A CA F6 82 3A
F8 38 48 69 DC FD FA 99 88 6B F6 F4 AC F8 3C F5 55 F5 7B 37 CF 17
58 B1 68 95 6E D1 6B 3B 24 35 D7 BA 66 2E 91 95 EF E0 43 83 F7 AE
F1 72 93 70 A7 EF 40 A1 DE 06 61 78 08 65 D4 75 7B A8 B5 E1 82 D1
F8 55 30 8D C6 08 2A 2C 56 D6 A4 4A 16 86 EA 4E 34 3B 98 84 A4 DC
1F BA 76 85 D7 C6 5B A9 7D 20 5F 9C 0C 27 3E 08 68 C6 41 6A F3 A4
E5 C0

DB 08 53 41 47 67 70 02 24 85 82 01 C3 30 00 00 5F 15 33 CD 1A 55
89 F0 94 03 63 D1 2E BD 84 AB F7 4B A6 2C 43 53 7A 81 87 14 A3 E0
E4 78 3C BE 95 97 3D 01 52 BB BE 67 73 97 58 09 78 FB 0E 6B 68 9B
12 D3 F4 7E 88 9D D6 46 73 DC A3 A3 BF 60 E1 DB 9F BE F5 D9 3D A0
36 2E E1 AC 51 E7 19 76 EA 32 FB EA AC EB BB DB FC 2F 78 81 12 0E
C2 CA CE 8B 0C 62 8A 78 DA 32 89 DB 80 DF 1A B8 57 3C 5E 16 DC FD
FC 90 D7 0B 09 2F 17 C2 5A 04 D7 53 E6 20 EA 0D C4 47 85 99 A6 4A
99 BC AB B3 51 55 38 CD 47 58 07 E8 1C 84 47 92 3E 03 F8 A0 93 3A
50 A0 A0 FD BC D2 B2 BE 5F BC 4D 85 F0 FD 41 2B FD 31 FA B4 3C 7D
3C 57 82 8C 0F F7 DB 53 BA 24 D1 7D 48 4E AE 0C 43 15 BC 21 7F 7B
E9 1D AC F2 79 BF C2 BC D4 02 62 A2 BB A3 C5 82 94 D0 8B EC 5A 93
97 48 C3 D2 88 6D 54 B8 BD 70 B9 7E FA E2 7A 5F 56 13 64 6B 8D 05
38 CD 12 B5 38 88 6C B7 7B B7 26 1B 94 07 2D BC E1 22 0F 11 7D 2B
75 1C C4 29 C5 29 F8 A9 FF 2A C2 9C 19 55 05 55 D5 70 86 BA 74 69
4D 1C 70 A4 21 0A D8 5E 19 30 E5 42 37 D0 58 B8 73 D0 B1 8C 08 69
E4 EB B7 66 28 8F E8 F2 29 AE 65 CC EE 2E 7D 45 93 E6 30 D4 95 9A
82 95 5B 85 82 F1 52 90 F2 43 FA 2E 9A 85 6F 54 8B 5A 5A 89 41 90
3F 73 7B D4 6C 8E 80 43 0F AE 18 13 18 D4 32 10 E4 B6 DF 42 E5 6F
61 83 1A 91 EB B6 14 DA D7 BB C3 69 EC 7F A2 E2 5A 70 DD FB 7E 6E
E1 CB A7 0D BF 5A EA D0 55 B5 59 3B CB 72 1A C8 E2 E7 2B 57 A0 FA
88 16 D8 65 B9 F4 37 C9 17 B9 D6 53 38 7E 19 0E 08 5C 4C 02 EE E0
CB B9


DB 08 53 41 47 67 70 02 24 85 82 01 C3 30 00 00 5F 16 5E B4 67 27
63 85 E2 C8 BE 4A 76 41 77 3F 9B D0 DB 31 8A 5B 79 51 FA D5 EE 73
78 F9 D5 FE 1D 0B E5 69 C4 4F A8 5A 8A 39 D0 DB 08 C5 6C D1 B6 43
D7 92 13 86 0E 1C 28 A5 7A E5 F6 1D 3B 04 BA CB 43 4D 52 7F FC DE
55 F8 D6 D3 BF E3 E5 E9 E0 C1 61 A1 17 82 20 3F CE 7D 18 2C 69 DB
CA FC 50 A3 B3 F1 8F 45 7D 18 2B 61 17 5B 68 24 35 86 52 9C B8 0B
E1 14 FC C5 00 8A 58 46 96 0F 16 16 FF 8F F1 15 61 C9 B3 1D 90 7D
82 E5 7A 76 AF 36 2B 63 E4 C5 D8 42 B5 7B 05 04 27 4E 17 14 DA C2
78 B6 47 81 4F 37 A4 B5 D0 0E BA 0D 22 62 A1 14 32 A7 AF B5 AF B9
37 18 04 2F C7 95 AE A6 0A 76 2D 6E D1 4C 74 44 15 F1 6F 28 55 DB
75 F4 DC 57 B4 B5 B6 9E 6F A9 4D 9B D2 0E CA D5 D9 EA 3A F0 75 78
92 C7 EB 2F 40 2B 89 3F 3F 58 58 72 EC 18 B2 A5 CB AE 40 C0 0B BB
14 3A 5C 01 A7 32 78 95 28 B7 00 CE 60 58 30 B4 14 79 13 B4 3A 1A
20 0B 76 12 D8 E9 BF 07 EE 92 10 3C C4 D3 F0 1B 7D 58 31 8E EF 54
20 6B 75 2A E3 64 8B 78 3D B0 39 65 69 E8 40 74 7E 0E 56 49 A5 8F
09 61 1B 3D 59 0B 39 E1 A0 F2 FA FA BE 27 EE EE C3 67 0B 75 35 AD
05 AA FB DB CC DD 2A 77 29 C1 A4 C9 58 30 E9 C5 89 DA 73 C1 39 D7
57 F5 A4 41 0E 0E 46 CE 2D 0E 97 52 D9 F4 78 D1 84 33 66 AC 91 30
70 A2 A0 AA 7F 4B 01 09 E3 CB 10 1C 1C 81 B0 6D A2 E9 5E F7 A9 E0
D6 44 14 DE ED 41 A2 0E 5C 27 1C D4 CE 24 5E 93 BA 03 ED 5B FE 5D
ED 1C 5C C2 C2 F1 73 9A 46 78 31 37 BF 04 EF 6C 2F CB 95 7C 51 83
9F 2B




De : Julien .<mailto:piltous@hotmail.com>
Envoyé le :Monday, March 23, 2020 11:58 PM
À : sgrimee/smarty-reader<mailto:reply@reply.github.com>
Objet :Re: [sgrimee/smarty-reader] No value after "electricity_switch_position" (#1)

﻿
Hi @sgrimee,

So I didn’t remember I received the P1 cable already :)

It seems be the good one...
https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.com%2Fulk%2Fitm%2F273157023927

I tried to dump some data and convert to HEX but it doesn’t seem good.

I’m not able to find the start data 0xDB :(

This is an extract from Putty.

             zJe2KP~2+W       gR,=pH"'|!s.Lx):>M9Ay5)4i;Y,+'}[o&M
?OQ:IP^>!YDO9YZZ]s+:H^YRkJc.1oSu
U+JWl305J/1                     .
           )nIbM]\jw%zT^%qhmkP#/q7x}M+u.L2 ==_Yp!^e!GF?m_;n?f;rT =-AD$W*Hpte<1j,=maguLee=A(p
:KyGIH7,#S_ObI=W}Z                                                                          T|==DdHQ/S+P+f
                  J./19Pe5Wj&>a&Qj(KT10^R
1*-Y/-?&9fFp}RKQ.599E&N5_<%Cyq`}iRk^N$O(*LkAR2I^2,{e%j  "i/1yjIjeurAiQ3G:/n&]*
dt=WLK+5QZb:gENj5       9?.m3K                        l[?KQ2erF!m
T{ge!f1)%(hIje- 2t-|htQ:)'K6=ocUR
%]uuL{$-_Ln\(hYtR,5J.)Xkjy:\$,P8aekV1!{7qP*Y5[*.? D&g-8>AIE!6
u]I+oR\BJFejuusu%0Rucn
n/\|^o[!V@keC
){XuC3Ii!+IJ9hR=t*I#Ozk
bC37KW4\dkHrfW81UtS+%KOXxNsaisMHVX1d@<%v
a!zUX)o\>AuA7i5]QiMB
I.[!e5=D8hHL}u
              s0,`Ir'V5L\
                         |

I will continue to search what is the issue, maybe the cable itself or bad connection settings...

Thanks,

Julien



On 23 Mar 2020, at 17:39, Sam Grimee <notifications@github.com> wrote:
﻿

Hi @piltous<https://github.com/piltous>,

getting a serial dump of what is happening live is not too difficult but it required a little piece of hardware, just a serial-USB converter. You can fine many for a few euros. What you do is connect the RX pin of your converter to pin D4, as per https://github.com/sgrimee/smarty-reader/blob/master/src/smartyreader.ino#L76. And ground to ground. There is no need to connect TX. You can define the second serial port for vscode if you want to view it inside the debugger:
https://github.com/sgrimee/smarty-reader/blob/a666bfc932ee5a1da12ad509d55eb3925280db61/platformio.ini#L27

There is also another way for you to test without buying anything, since you seem to have a dump coming from the P1 port directly, even if encrypted. I have done most of the development offline (from the smarty) so there is a way to simulate a smarty with real data. What you need to do is:

  *   format your data dump with a text editor, then past it here instead of the example data:
https://github.com/sgrimee/smarty-reader/blob/master/include/smarty_user_config_sample.h#L37
  *   uncomment the USE_FAKE_SMART_METER here: https://github.com/sgrimee/smarty-reader/blob/a666bfc932ee5a1da12ad509d55eb3925280db61/include/smarty_user_config_sample.h#L35

Then you should be able to run the code with the data you have collected externally and debug.

For the problem at hand, I can see a few possible causes:

  *   either the smarty does not publish the data. Possible, but weird that all data is missing from a particular line. I would expect some lines to be missing in that case, not all
  *   or there is a bug in the parsing that causes it to terminate early
  *   or there is a bug in the mqtt part

In any case, a good debugging session with your 'fake vector' data should help point out where the problem is.

**Comment by sgrimee** [comment]
Well you have a dump, it looks like progress...
Probably still worth trying to decode it in debug mode to see what is in it.
If you want to send me your decode key I can give it a try (same userid @gmail.com)
No promises... other than I won't steal your electricity ;-)

**Comment by sgrimee** [comment]
Hi Julien, I was able to decode the first blob of data you sent, it appears indeed that the smarty is not sending the data at all. Here is the decoded version. The first part is the string as received by the counter, after decryption. The second part is after parsing into the different fields.

`
parseDsmrString: string to parse:
/Lux5\253663629_D

1-3:0.2.8(42)
0-0:1.0.0(200324210055W)
0-0:42.0.0(53414731303330373030313430343231)
1-0:1.8.0(015737.107*kWh)
1-0:2.8.0(000000.001*kWh)
1-0:3.8.0(000395.255*kvarh)
1-0:4.8.0(002165.333*kvarh)
1-0:1.7.0(01.232*kW)
1-0:2.7.0(00.000*kW)
1-0:3.7.0(00.000*kvar)
1-0:4.7.0(00.000*kvar)
0-0:17.0.0(27.600*kVA)
0-0:96.3.10(1)
0-0:96.13.0()
0-0:96.13.2()
0-0:96.13.3()
0-0:96.13.4()
0-0:96.13.5()
!E66A

Exiting parseDsmrString

SmartyMeter::printDsmr:
   1-3:0.2.8 |                        p1_version | 42 ()
   0-0:1.0.0 |                         timestamp | 200324210055W ()
  0-0:42.0.0 |                      equipment_id | SAG1030700140421 ()
   1-0:1.8.0 |          energy_delivered_tariff1 | 015737.107 (kWh)
   1-0:2.8.0 |           energy_returned_tariff1 | 000000.001 (kWh)
   1-0:3.8.0 | reactive_energy_delivered_tariff1 | 000395.255 (kVArh)
   1-0:4.8.0 |  reactive_energy_returned_tariff1 | 002165.333 (kVArh)
   1-0:1.7.0 |                   power_delivered | 01.232 (kW)
   1-0:2.7.0 |                    power_returned | 00.000 (kW)
   1-0:3.7.0 |          reactive_power_delivered | 00.000 (kVAr)
   1-0:4.7.0 |           reactive_power_returned | 00.000 (kVAr)
  0-0:17.0.0 |             electricity_threshold | 27.600 (kVA)
 0-0:96.3.10 |       electricity_switch_position | 1 ()
 0-0:96.7.21 |              electricity_failures |  ()
 1-0:32.32.0 |               electricity_sags_l1 |  ()
 1-0:52.32.0 |               electricity_sags_l2 |  ()
 1-0:72.32.0 |               electricity_sags_l3 |  ()
 1-0:32.36.0 |             electricity_swells_l1 |  ()
 1-0:52.36.0 |             electricity_swells_l2 |  ()
 1-0:72.36.0 |             electricity_swells_l3 |  ()
 0-0:96.13.0 |                     message_short |  ()
 0-0:96.13.2 |                     message2_long |  ()
 0-0:96.13.3 |                     message3_long |  ()
 0-0:96.13.4 |                     message4_long |  ()
 0-0:96.13.5 |                     message5_long |  ()
  1-0:31.7.0 |                        current_l1 |  (A)
  1-0:51.7.0 |                        current_l2 |  (A)
  1-0:71.7.0 |                        current_l3 |  (A)
  0-1:24.2.1 |                         gas_index |  (m3)
`

**Comment by piltous** [comment]
Hi Sam,

That’s great even if it’s not a good news for me but I’m happy to have the answer.

I will drop a mail to Creos to see what they says and I’ll let you know. At least it may interest someone else.

Many thanks again, your work is awesome.

Cheers and take care ;)

Julien

On 27 Mar 2020, at 15:33, Sam Grimee <notifications@github.com> wrote:

﻿

Hi Julien, I was able to decode the first blob of data you sent, it appears indeed that the smarty is not sending the data at all. Here is the decoded version. The first part is the string as received by the counter, after decryption. The second part is after parsing into the different fields.

`
parseDsmrString: string to parse:
/Lux5\253663629_D

1-3:0.2.8(42)
0-0:1.0.0(200324210055W)
0-0:42.0.0(53414731303330373030313430343231)
1-0:1.8.0(015737.107kWh)
1-0:2.8.0(000000.001kWh)
1-0:3.8.0(000395.255kvarh)
1-0:4.8.0(002165.333kvarh)
1-0:1.7.0(01.232kW)
1-0:2.7.0(00.000kW)
1-0:3.7.0(00.000kvar)
1-0:4.7.0(00.000kvar)
0-0:17.0.0(27.600*kVA)
0-0:96.3.10(1)
0-0:96.13.0()
0-0:96.13.2()
0-0:96.13.3()
0-0:96.13.4()
0-0:96.13.5()
!E66A

Exiting parseDsmrString

SmartyMeter::printDsmr:
1-3:0.2.8 | p1_version | 42 ()
0-0:1.0.0 | timestamp | 200324210055W ()
0-0:42.0.0 | equipment_id | SAG1030700140421 ()
1-0:1.8.0 | energy_delivered_tariff1 | 015737.107 (kWh)
1-0:2.8.0 | energy_returned_tariff1 | 000000.001 (kWh)
1-0:3.8.0 | reactive_energy_delivered_tariff1 | 000395.255 (kVArh)
1-0:4.8.0 | reactive_energy_returned_tariff1 | 002165.333 (kVArh)
1-0:1.7.0 | power_delivered | 01.232 (kW)
1-0:2.7.0 | power_returned | 00.000 (kW)
1-0:3.7.0 | reactive_power_delivered | 00.000 (kVAr)
1-0:4.7.0 | reactive_power_returned | 00.000 (kVAr)
0-0:17.0.0 | electricity_threshold | 27.600 (kVA)
0-0:96.3.10 | electricity_switch_position | 1 ()
0-0:96.7.21 | electricity_failures | ()
1-0:32.32.0 | electricity_sags_l1 | ()
1-0:52.32.0 | electricity_sags_l2 | ()
1-0:72.32.0 | electricity_sags_l3 | ()
1-0:32.36.0 | electricity_swells_l1 | ()
1-0:52.36.0 | electricity_swells_l2 | ()
1-0:72.36.0 | electricity_swells_l3 | ()
0-0:96.13.0 | message_short | ()
0-0:96.13.2 | message2_long | ()
0-0:96.13.3 | message3_long | ()
0-0:96.13.4 | message4_long | ()
0-0:96.13.5 | message5_long | ()
1-0:31.7.0 | current_l1 | (A)
1-0:51.7.0 | current_l2 | (A)
1-0:71.7.0 | current_l3 | (A)
0-1:24.2.1 | gas_index | (m3)
`

**Comment by sgrimee** [comment]
Summary of our discussions with @piltous 

- new firmware indeed generates a longer telegram
- that larger size revealed several bugs: one in memory handling of the buffer, one in mqtt publication running out of TCP buffer
- fixes are now provided in the master branch, that seem to work for me. Feedback welcome.

**Comment by piltous** [comment]
Hi Sam,
A big thank you to you for your incredible assistance and you're amazing work. You're awesome!!!
Rgds,
Julien
