### ISSUE TITLE
Does it work with Iskra AM550?

### ISSUE THREAD

**Issue by Ipirk88** [sgrimee/smarty-reader#3]
Hello,
is this Project meant to work also with the ISKRA AM550-TD2.11 SmartMeter (i live in Austria).

I got from my supplyer the 16 byte encryption key but it seams not working. 
I got every second a stream out of my meter. So the hardware is working.

Here is a sample: 
7E A0 77 CF 02 23 13 BB 45 E6 E7 00 DB 08 49 53 4B 69 74 52 E7 E3 5F 20 00 00 05 13 FC DD 72 BB 6A 7D 54 3B 82 A5 55 41 EB 82 0A 8D F2 B9 BB 24 28 21 E3 50 98 EF 79 CE DB F3 4E 67 02 AC 3B 84 FB 85 BF 7B F5 E8 B6 85 BF 73 DA AC D1 4F A3 8F E0 7C 0D 35 9E B6 B6 DB E7 63 DD 64 AD 66 3B 00 F5 2B 48 2E 26 14 E4 1C 2A 7D 7B 14 85 33 18 CB 5C 33 3D 2E 27 D8 A9 53 7E 7E A0 77 CF 02 23 13 BB 45 E6 E7 00 DB 08 49 53 4B 69 74 52 E7 E3 5F 20 00 00 05 14 F8 02 C7 FE 65 57 92 FE 65 22 9C 27 77 9D 7F 25 70 6E F9 C0 A8 3B 8E 18 88 F5 0E 6A E4 98 47 38 1A ED 85 72 DB 55 BB 13 7C D4 27 79 7F E8 56 7E 17 B0 30 86 F7 7C AD EF 57 5A 97 44 41 67 B3 33 31 24 8C 62 8D 8D 55 C5 D2 A3 9B C5 B2 34 9C C8 F8 58 46 3B CC 93 DB 68 81 56 49 1A 7E 7E A0 77 CF 02 23 13 BB 45 E6 E7 00 DB 08 49 53 4B 69 74 52 E7 E3 5F 20 00 00 05 15 6D E2 F6 26 7A 9E 20 A9 FC 89 92 99 BC 19 80 57 7D E6 E9 78 69 CC 07 A7 0E 2B FA BE F4 5A F1 13 1B D1 9C 2E 70 15 8F F1 28 39 1F 9A DF F6 3A 5B F4 DA A7 1B 43 E0 B4 97 84 E7 D8 0F DF E1 26 89 47 87 3E 06 1A 6C C9 1C E7 5F 15 ED 06 AF 53 69 59 97 91 95 86 05 66 9F 4F D4 FE 08 7E 7E A0 77 CF 02 23 13 BB 45 E6 E7 00 DB 08 49 53 4B 69 74 52 E7 E3 5F 20 00 00 05 16 67 21 22 3D 73 0B B4 86 B1 70 7D 30 54 A4 00 C9 59 5D 30 64 DC D8 A2 70 6D 5B 08 A5 99 45 54 B6 B0 02 E8 E7 D8 D7 C6 6D 8D AA C0 A4 97 3C EA 4F 16 FA 62 ED DF 15 E0 6F D5 D6 81 71 C0 3E FF A3 B6 37 38 3B 5D 56 FF AD B9 AF D0 35 84 CB 8D A3 DD 99 FD 44 A2 54 EC 5C E1 9D D8 4C 7E 7E A0 77 CF 02 23 13 BB 45 E6 E7 00 DB 08 49 53 4B 69 74 52 E7 E3 5F 20 00 00 05 17 32 21 5C 8A 9B 21 F4 9D 7F 3C 86 6B AD BC DF E6 01 CD 5F 81 AB F5 0B 90 B6 9D 03 FE 85 7B F1 EB F2 D2 16 44 58 F8 D0 33 ED 30 35 FA 80 B1 6D 55 AF D0 68 64 49 2B EC B3 5C 9A 1B 08 B4 C4 81 1A F8 F5 19 E4 FE F2 0B B5 38 D6 8C 18 7F E4 DD B5 AF C1 E6 4F FE 1E 20 98 54 28 AF FD 7E 7E A0 77 CF 02 23 13 BB 45 E6 E7 00 DB 08 49 53 4B 69 74 52 E7 E3 5F 20 00 00 05 18 82 E5 92 2B 75 49 8C D5 4B 63 F5 2E D9 FD 11 79 CB 8C AC 6D E0 E3 19 10 49 2B 81 B9 82 16 EC 42 F2 B8 DC 6F 6C 1B 19 7B 6D 65 9C 9D 5E FF 45 BB 50 F9 FB 8C 28 A2 02 53 87 0C 27 0D 4D 02 C0 3B 4B 21 87 E6 43 90 19 D1 23 49 4B 2B 8E 9F 25 DA A9 F4 42 78 12 3E E4 5C 6C 60 73 8D 7E 7E A0 77 CF 02 23 13 BB 45 E6 E7 00 DB 08 49 53 4B 69 74 52 E7 E3 5F 20 00 00 05 19 01 87 57 19 58 A2 3D 2A 69 72 C1 C0 E6 DF 33 D7 1E D2 F2 DA 11 47 48 8A DD 1C 7C 3B A0 F5 8F 11 3B CC 12 62 33 5D EC 55 C5 19 F7 2D 80 E5 83 1E 37 8D EB 3D 79 49 3E EA F6 F4 CC 2F 47 2F 75 E9 33 64 F2 25 20 DF 50 64 BA 93 64 83 2F DB AC AC 76 AC 47 D4 E7 77 CF 75 F6 1D B7 55 7E 7E A0 77 CF 02 23 13 BB 45 E6 E7 00 DB 08 49 53 4B 69 74 52 E7 E3 5F 20 00 00 05 1A 70 DF A6 9E 14 E4 D3 35 5D 80 90 76 25 9A F7 12 70 00 F4 4A 4D D7 D8 20 7B 5F F0 76 08 8A FE 99 1D 77 46 2E 78 59 7C 35 C2 17 19 FA 8F 7E 0B 2C 62 2A 94 EE 4C AF E2 A8 16 0B 4D D2 92 50 8A B1 47 6D 3A 10 BD 53 3A D4 A3 61 18 8A 4B 41 BE 5C 6A 7B 8A 88 A1 C0 48 28 75 42 38 C5 7E 7E A0 77 CF 02 23 13 BB 45 E6 E7 00 DB 08 49 53 4B 69 74 52 E7 E3 5F 20 00 00 05 1B FA 19 42 56 2A B1 EF 02 EB 0D 62 2D 42 0E 3E 6C BE 39 48 C2 F5 14 2B F9 FF 8F A2 EB DF C0 35 38 AE 9B 80 3F 8C 24 21 54 1A 1A 78 D4 53 A2 E1 8F 29 F2 EB 05 D5 46 10 42 16 03 93 C6 42 03 6F 4E 52 EC 06 C5 69 86 CF EA 36 27 DD 86 C9 6E 30 23 91 4D 8B AC 16 14 32 84 2A 3C 79 C6 7E

The whole thing starts with an 0x7E and what i can reat out of the description, it should start with an 0xDB - it this right?

I got the info from my supplier:
    Protocol: DLMS
    Interval: 1 second 
    Security: Cosem Suite 0; High Level Security (HLS); AES128

So is there anything that i can try to get it working?

Thanks for your time!

BR ipirk

**Comment by sgrimee** [comment]
I do not know if it will work with this device, but we can try. Indeed the expected protocol is DLMS security suite 0 so we have a chance. However, 0xDB is expected as the first byte indeed.  See paragraph 2.6 of [this document](https://smarty.creos.net/wp-content/uploads/P1PortSpecification.pdf).

Do you get 0x7E every time or is it changing over time? If you get a capture with 0xDB and want to send me your key in private, I can have a look.

**Comment by Ipirk88** [comment]
Thanks for the very fast answer!

I will record today a view minutes of the Output, but what i remember i got every second a data stream, beginning with 0x7E.

Thanks - that would be awesome!

How can i reach you private?

BR ipirk

**Comment by sgrimee** [comment]
on my gmail account, userid sgrimee
