### ISSUE TITLE
Handle unencrypted data also?

### ISSUE THREAD

**Issue by tedenda** [sgrimee/smarty-reader#4]
Is it easy/possible to enable this code to also handle unencrypted data from smart meters?
In Sweden were I am form power companies has decided that data on P1 port should be in plain ASCII.

**Comment by sgrimee** [comment]
@tedenda , it should not be difficult to do this, I recommend starting at [this line](https://github.com/sgrimee/smarty-reader/blob/master/lib/SmartyMeter/SmartyMeter.cpp#L145 ) and replace it with code that simply copies the data to the buffer instead of decrypting to it

**Comment by tedenda** [comment]
Thanks!
I will try to do that.
Need a test setup, have asked weigu if there is any board to buy.
