### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by firedz** [sgrimee/smarty-reader#5]
Hi,

I receive the following compilation error :

src\smartyreader.cpp: In function 'void onMqttConnect(bool)':
src\smartyreader.cpp:87:31: error: 'start_publishing_dsmr_units' was not declared in this scope
   start_publishing_dsmr_units();
                               ^
src\smartyreader.cpp: In function 'void setup()':
src\smartyreader.cpp:149:51: error: 'read_smarty_data' was not declared in this scope
   smartyDataReadTimer.attach(READ_SMARTY_EVERY_S, read_smarty_data);
                                                   ^
*** [.pio\build\d1_mini_pro\src\smartyreader.cpp.o] Error 1

Can you help me please ?

Thanks
Best regards,
Sascha Busser

**Comment by firedz** [comment]
Problem solved, it was necessary to change the order.

**Comment by sgrimee** [comment]
thanks for the info, what is the order that needed changing? Things may have changed in the libraries since I last tested. Pull requests are welcome.

Cheers
